### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by pribadihcr** [ReubenBond/HanBaoBao#1]
Hi @ReubenBond,

How to use the app.?

**Comment by ReubenBond** [comment]
Have you installed it? Copy some Chinese text and the app will transliterate it for you.

Video of an older version:
https://www.youtube.com/watch?v=a9x9MBoLfxs

Play store link:
https://play.google.com/store/apps/details?id=com.tallogre.hanbaobao

**Comment by pribadihcr** [comment]
Hi @ReubenBond,

I installed via this repo, the icon can not be shown like the video in youtube. Anyway, I have installed it via play store and its work. wow, this app is very useful. Thanks
